name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Read artifact name, version
        shell: bash
        run: |
          echo "artifact_id=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.artifactId -q -DforceStdout=true)" >> $GITHUB_ENV
          echo "artifact_version=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout=true)" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Copy jar files to staging
        shell: bash
        run: |
          mkdir staging && cp target/${{ env.artifact_id }}-${{ env.artifact_version }}.jar staging
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: staging/*
          tag_name: "v${{ env.artifact_version }}-${{ github.sha }}"
          prerelease: false
          body: 'Package for commit: ${{ github.sha }}'
          make_latest: "true"
